### ISSUE TITLE
Crash in first iteration

### ISSUE THREAD

**Issue by trquinn** [paratreet/paratreet#11] opened 2020-06-23 20:33 UTC
This is with charm v6.10.1:
I get:
```
./paratreet -f ../inputgen/tipsyParticles.dat -i 1
Charm++> No provisioning arguments specified. Running with a single PE.
         Use +auto-provision to fully subscribe resources or +p1 to silence this message.
Charm++: standalone mode (not using charmrun)
Charm++> Running in SMP mode: 1 processes, 1 worker threads (PEs) + 1 comm threads per process, 1 PEs total
Charm++> The comm. thread both sends and receives messages
Converse/Charm++ Commit ID: v6.10.1-0-gcc60a79
Warning> Randomization of virtual memory (ASLR) is turned on in the kernel, thread migration may not work! Run 'echo 0 > /proc/sys/kernel/randomize_va_space' as root to disable it, or try running with '+isomalloc_sync'.
Charm++> scheduler running in netpoll mode.
CharmLB> Load balancer assumes all CPUs are same.
Charm++> Running on 1 hosts (1 sockets x 4 cores x 2 PUs = 8-way SMP)
Charm++> cpu topology info is gathered in 0.003 seconds.

[PARATREET]
Input file: ../inputgen/tipsyParticles.dat
Decomposition type: OCT
Tree type: OCT
Maximum number of particles per treepiece: 1000
Maximum number of particles per leaf: 10

* Initialization
Loading Tipsy data and building universe: 5.380 ms
Universal bounding box: <10000, 1.000, 6.115, {(-16.840 -15.953 -15.521),(16.346 15.078 15.849)}> with volume 32303.570
Assigning keys and sorting particles: 11.924 ms
Setting up splitters for decomposition: 0.170 ms
Created 50 TreePieces: 1.038 ms
Flushing particles to TreePieces: 1.207 ms
* Iteration 0
Tree build: 17.661 ms
Received data from 7 TreeCanopies
Broadcasting top 3 levels to caches
[CacheManager 0] receiving starter pack, size = 5
TreeCanopy cache loading: 0.118 ms
Tree traversal: 240.762 ms
Interactions: 501.229 ms
Perturbations: 2.692 ms
------------- Processor 0 Exiting: Called CmiAbort ------------
Reason: [0] Assertion "i < localElemVec.size()" failed in file ckarray.C line 1558.

[0] Stack Traceback:
  [0:0] paratreet 0x63e836 CmiAbortHelper(char const*, char const*, char const*, int, int)
  [0:1] paratreet 0x63e94d 
  [0:2] paratreet 0x648f2a 
  [0:3] paratreet 0x5e88e7 CkArray::recvBroadcast(CkMessage*)
  [0:4] paratreet 0x58847c CkDeliverMessageFree
  [0:5] paratreet 0x58be39 _processHandler(void*, CkCoreState*)
  [0:6] paratreet 0x646300 CsdScheduleForever
  [0:7] paratreet 0x64663d CsdScheduler
  [0:8] paratreet 0x643ada 
  [0:9] paratreet 0x643f1c ConverseInit
  [0:10] paratreet 0x57a307 charm_main
  [0:11] libc.so.6 0x7fcfd8774555 __libc_start_main
  [0:12] paratreet 0x51a5c3 
CHARM++ FATAL ERROR: [0] Assertion "i < localElemVec.size()" failed in file ckarray.C line 1558.

Segmentation fault (core dumped)
```
If I comment out the treepieces::ckDestroy() at line 196 of Driver.h, then it runs.

**Comment by AjayMT** [comment] 2020-06-24 03:47
I tried changing ckarray.C to investigate. This is the assertion that fails:
```c++
void CkArray::recvBroadcast(CkMessage *m)
{
  // ...
  int len = localElemVec.size();

  // ...

  {
    // ...
    for (unsigned int i = 0; i < len; ++i) {
      //...
      bool doFree = false;
      if (stableLocations && i == len-1) doFree = true;
#if CMK_ONESIDED_IMPL
      if (zc_msgtype == CMK_ZC_BCAST_RECV_DONE_MSG) doFree = false;
#endif
      CmiAssert(i < localElemVec.size()); // <== this one
      broadcaster->deliver(msg, (ArrayElement*)localElemVec[i], doFree);
    }
  // ...
}
```
As far as I can tell, `len` is not modified up to this point, so `localElemVec` must be changing. I removing the assertion and printing out `i`, `len` and `localElemVec`:
```c++
// CmiAssert(i < localElemVec.size());
if (i >= localElemVec.size() || len != localElemVec.size()) {
  printf("i %u sz %lu len %d\n", i, localElemVec.size(), len);
}
```
I saw this output:
```
...
* Iteration 0
Tree build: 17.965 ms
Received data from 7 TreeCanopies
Broadcasting top 3 levels to caches
[CacheManager 0] receiving starter pack, size = 5
TreeCanopy cache loading: 0.347 ms
Tree traversal: 29.755 ms
Interactions: 22.133 ms
Perturbations: 0.527 ms
i 1 sz 16 len 17
i 2 sz 15 len 17
i 1 sz 15 len 16
i 3 sz 14 len 17
i 2 sz 14 len 16
i 4 sz 13 len 17
i 3 sz 13 len 16
i 4 sz 12 len 16
i 5 sz 11 len 16
i 5 sz 12 len 17
i 6 sz 10 len 16
i 6 sz 11 len 17
i 1 sz 16 len 17
i 2 sz 15 len 17
i 7 sz 9 len 16
i 3 sz 14 len 17
i 4 sz 13 len 17
i 8 sz 8 len 16
i 5 sz 12 len 17
i 7 sz 10 len 17
i 6 sz 11 len 17
i 9 sz 7 len 16
i 10 sz 6 len 16
i 7 sz 10 len 17
...
```

It looks like `i + localElemVec.size() == len`, so perhaps `localElemVec` is shrinking by 1 each iteration? I am not entirely sure what the issue is, perhaps someone who has worked on the charm++ RTS can weigh in.

Removing this assertion didn't seem to break paratreet. I observed this issue and tested this on the `netlrts-darwin-x86_64-smp` build of charm.

**Comment by Wingpad** [comment] 2020-06-24 12:44
This may be a symptom of aggregating variable-sized messages, as `v6.10.1` does not include VarTRAM which we now rely on. This is supported somewhat by Ajay's observation that the issue does not arise on the latest development version of Charm++.

**Comment by minitu** [comment] 2020-06-24 21:42
Looks like the assertion error happens with `--enable-error-checking`, as `./build charm++ pamilrts-linux-ppc64le smp -j -g -O0 --disable-error-checking` does not exhibit this error but `./build charm++ pamilrts-linux-ppc64le smp -j -g -O0 --enable-error-checking` does.

**Comment by minitu** [comment] 2020-06-24 22:18
Not a TRAM related issue, removing `[aggregate]` from CacheManager entry methods still gives me the same errors.

**Comment by minitu** [comment] 2020-06-25 02:25
Fixed the issue by changing `treepieces.ckDestroy()` to `for (int i = 0; i < n_treepieces; i++) treepieces[i].ckDestroy()` (merged in `master`). Not sure if it is illegal to call ckDestroy() on a chare array proxy, but the manual says to call ckDestroy for each array element (https://charm.readthedocs.io/en/latest/charm++/manual.html#destroying-array-elements). @trquinn Please check if the issue is fixed now.

**Comment by minitu** [comment] 2020-09-17 18:00
Closing as it should be fixed.

**Closed by minitu** 2020-09-17 18:00 UTC
